title: Matematikk 1T
author: Edvard Munch Videregående Skole
copyright: "2024"
logo: ./evg_logo_med_1T.jpg
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", README.md]


options:
  numbered: true

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - html_image
    - deflist
    - tasklist
    - attrs_inline
    - attrs_block
    - smartquotes
    - colon_fence

latex:
  header_includes:
    - \usepackage{polynom}
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/reneaas/matematikk_1t/
  path_to_book: book/
  branch: main/


# launch_buttons:
  # notebook_interface: "jupyterlab"  # or "classic"
  # binderhub_url: "https://mybinder.org/"
  # thebe: true
  # colab_url: "https://colab.research.google.com"


html:
  use_issues_button: true
  use_repository_button: true
  nb_number_source_lines: false
  extra_js:
    - _static/custom.js
    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.4/mermaid.min.js


sphinx:
    # nb_number_source_lines: true    # Enables line numbers in code

  extra_extensions:
    - sphinx_proof
    - sphinx_inline_tabs
    - sphinxmermaid
    - sphinxcontrib.tikz
    - sphinx_jupyterbook_latex

  extra_css_files:
    - _static/


  config:
    language: norwegian
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3.2/es5/tex-mml-chtml.js
    html_theme_options:
      pygments_light_style: "github-light"
      pygments_dark_style: "one-dark"
    templates_path:
      - "_templates"