title: Matematikk 1T
author: Edvard Munch Videregående Skole
copyright: "2024"

options:
  numbered: true


execute:
  execute_notebooks: off

parse:
  # number_source_lines: true
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath
    - html_image
    - deflist
    - attrs_inline

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/reneaas/matematikk_1t/
  path_to_book: book/
  branch: main/


# launch_buttons:
  # notebook_interface: "jupyterlab"  # or "classic"
  # binderhub_url: "https://mybinder.org/"
  # thebe: true
  # colab_url: "https://colab.research.google.com"


html:
  use_issues_button: true
  use_repository_button: true
  nb_number_source_lines: false


sphinx:
    # nb_number_source_lines: true    # Enables line numbers in code
  extra_extensions:
    - sphinx_proof
    - sphinx_inline_tabs
    - sphinxmermaid
    - sphinxcontrib.tikz
  extra_css_files:
    - _static/
  config:
    language: norwegian
    # html_extra_path: ["book/rette_linjer/representasjoner/figurer/interaktive_plot/"]